import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import ThankYouModal from "../components/ThankYouModal";

export default function Home() {
  const [inputValue, setInputValue] = useState("");
  const [openModal, setOpenModal] = useState(false);
  const clickHandler = () => {
    const choiceA = "choice1";
    const choiceB = "choice2";

    if (inputValue === choiceA) {
      window.open("https://www.google.com/", "_blank");
    } else if (inputValue === choiceB) {
      window.open("https://www.facebook.com/", "_blank");
    } else {
      setOpenModal(true);
    }
  };
  return (
    <div className={styles.container}>
      {openModal && (
        <ThankYouModal
          closeModal={setOpenModal}
          inputText={inputValue}
          setInputText={setInputValue}
        />
      )}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Lorem Ipsum</h1>
      <p>Lorem ipsum dolor sit amet.</p>
      <div className={styles.inputDiv}>
        <input
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          placeholder="Enter your choice"
          type="text"
          maxLength="80"
        />
        <button onClick={clickHandler}>Submit</button>
      </div>
    </div>
  );
}
